server:
  port: ${PORT:8002}
spring:
  application:
    name: usuarios
  cloud:
    consul:
#      host: localhost
#      port: ${server.port}
      discovery:
        enabled: true
        register: true
        service-name: mcs-${spring.application.name}
        instance-id: ${spring.application.name}:${vcap.application.instance_id:${spring.application.instance_id:${random.value}}}
  config:
    import: optional:configserver:http://tesis-config:8888
  # PostgreSQL properties
  datasource:
    url: jdbc:postgresql://localhost:5432/asistanstDB
    username: postgres
    password: admin
    driver-class-name: org.postgresql.Driver
  # Hibernate properties
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
  # Email properties
  mail:
    host: smtp.gmail.com
    port: 587
    protocol: smtp
    username: eep.esfot2022@gmail.com
    password: yyvh rasm vrtt emph
    properties:
      mail:
        smtp:
          auth: true
          quitwait: false
          starttls:
            enable: true
            required: true
logging:
  level:
    com.ecwid.consul: DEBUG
    org.springframework.cloud.consul: DEBUG
