server:
  port: 8091
spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: asistente
          uri: lb://mcs-asistente
          predicates:
            - Path=/api/asistente/**
          filters:
            - StripPrefix=2
        - id: usuarios
          uri: lb://mcs-usuarios
          predicates:
            - Path=/api/usuarios/**
          filters:
            - StripPrefix=2
        - id: chatbot
          uri: lb://nest-service
          predicates:
            - Path=/api/chatbot/**
          filters:
            - StripPrefix=2
    consul:
#      host: localhost
#      port: ${server.port}
      discovery:
        enabled: true
        register: true
        service-name: ${spring.application.name}
        instance-id: ${spring.application.name}:${vcap.application.instance_id:${spring.application.instance_id:${random.value}}}
  config:
    import: optional:configserver:http://tesis-config:8888
logging:
  level:
    com.ecwid.consul: DEBUG
    org.springframework.cloud.consul: DEBUG
